-- DScope Camel Persistence + Audit schema (Snowflake)
-- Compatible with JdbcFlowStateStore table contracts.

CREATE SCHEMA IF NOT EXISTS CAMEL_AGENT;
USE SCHEMA CAMEL_AGENT;

CREATE TABLE IF NOT EXISTS CAMEL_FLOW_SNAPSHOT (
    FLOW_TYPE        VARCHAR(128) NOT NULL,
    FLOW_ID          VARCHAR(256) NOT NULL,
    VERSION          NUMBER(38,0) NOT NULL,
    SNAPSHOT_JSON    VARCHAR NOT NULL,
    METADATA_JSON    VARCHAR NOT NULL,
    LAST_UPDATED_AT  VARCHAR(64) NOT NULL,
    CONSTRAINT PK_CAMEL_FLOW_SNAPSHOT PRIMARY KEY (FLOW_TYPE, FLOW_ID)
);

CREATE TABLE IF NOT EXISTS CAMEL_FLOW_EVENT (
    FLOW_TYPE         VARCHAR(128) NOT NULL,
    FLOW_ID           VARCHAR(256) NOT NULL,
    SEQUENCE          NUMBER(38,0) NOT NULL,
    EVENT_ID          VARCHAR(128) NOT NULL,
    EVENT_TYPE        VARCHAR(128) NOT NULL,
    PAYLOAD_JSON      VARCHAR NOT NULL,
    OCCURRED_AT       VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY   VARCHAR(256),
    CONSTRAINT PK_CAMEL_FLOW_EVENT PRIMARY KEY (FLOW_TYPE, FLOW_ID, SEQUENCE)
);

CREATE TABLE IF NOT EXISTS CAMEL_FLOW_IDEMPOTENCY (
    FLOW_TYPE        VARCHAR(128) NOT NULL,
    FLOW_ID          VARCHAR(256) NOT NULL,
    IDEMPOTENCY_KEY  VARCHAR(256) NOT NULL,
    APPLIED_VERSION  NUMBER(38,0) NOT NULL,
    CONSTRAINT PK_CAMEL_FLOW_IDEMPOTENCY PRIMARY KEY (FLOW_TYPE, FLOW_ID, IDEMPOTENCY_KEY)
);

-- Search optimization for purge/audit predicates
ALTER TABLE CAMEL_FLOW_EVENT ADD SEARCH OPTIMIZATION ON EQUALITY(FLOW_TYPE, FLOW_ID, EVENT_TYPE);
ALTER TABLE CAMEL_FLOW_SNAPSHOT ADD SEARCH OPTIMIZATION ON EQUALITY(FLOW_TYPE, FLOW_ID);
