-- Purge script (Snowflake)
-- Criteria:
--   1) closed conversations only (agent.instance.closed event)
--   2) closed before timestamp
--   3) specific agent type/name (payload.agentName)

USE SCHEMA CAMEL_AGENT;

-- Input parameters (set as needed)
SET PURGE_BEFORE_TS = '2026-01-01T00:00:00Z';
SET PURGE_AGENT_NAME = NULL;
SET PURGE_REQUIRE_CLOSED = TRUE;

CREATE OR REPLACE TEMP TABLE PURGE_TARGET_CONVERSATIONS AS
WITH CLOSED_CONV AS (
    SELECT DISTINCT FLOW_ID AS CONVERSATION_ID
    FROM CAMEL_FLOW_EVENT
    WHERE FLOW_TYPE = 'agent.conversation'
      AND EVENT_TYPE = 'agent.instance.closed'
      AND TRY_TO_TIMESTAMP_TZ(OCCURRED_AT) <= COALESCE(TRY_TO_TIMESTAMP_TZ($PURGE_BEFORE_TS), CURRENT_TIMESTAMP())
),
AGENT_FILTERED AS (
    SELECT DISTINCT FLOW_ID AS CONVERSATION_ID
    FROM CAMEL_FLOW_EVENT
    WHERE FLOW_TYPE = 'agent.conversation'
      AND (
          TRY_PARSE_JSON(PAYLOAD_JSON):payload:agentName::STRING = $PURGE_AGENT_NAME
          OR TRY_PARSE_JSON(PAYLOAD_JSON):agentName::STRING = $PURGE_AGENT_NAME
      )
)
SELECT DISTINCT FLOW_ID AS CONVERSATION_ID
FROM CAMEL_FLOW_EVENT
WHERE FLOW_TYPE = 'agent.conversation'
  AND (
      $PURGE_BEFORE_TS IS NULL
      OR TRY_TO_TIMESTAMP_TZ(OCCURRED_AT) <= TRY_TO_TIMESTAMP_TZ($PURGE_BEFORE_TS)
  )
  AND (
      $PURGE_REQUIRE_CLOSED = FALSE
      OR FLOW_ID IN (SELECT CONVERSATION_ID FROM CLOSED_CONV)
  )
  AND (
      $PURGE_AGENT_NAME IS NULL
      OR FLOW_ID IN (SELECT CONVERSATION_ID FROM AGENT_FILTERED)
  );

CREATE OR REPLACE TEMP TABLE PURGE_TARGET_TASKS AS
SELECT FLOW_ID AS TASK_ID
FROM CAMEL_FLOW_SNAPSHOT
WHERE FLOW_TYPE = 'agent.task'
  AND TRY_PARSE_JSON(SNAPSHOT_JSON):conversationId::STRING IN (SELECT CONVERSATION_ID FROM PURGE_TARGET_CONVERSATIONS);

CREATE OR REPLACE TEMP TABLE PURGE_TARGET_ROUTES AS
SELECT FLOW_ID AS ROUTE_INSTANCE_ID
FROM CAMEL_FLOW_SNAPSHOT
WHERE FLOW_TYPE = 'agent.dynamicRoute'
  AND TRY_PARSE_JSON(SNAPSHOT_JSON):conversationId::STRING IN (SELECT CONVERSATION_ID FROM PURGE_TARGET_CONVERSATIONS);

SELECT 'target_conversations' AS METRIC, COUNT(*) AS VALUE FROM PURGE_TARGET_CONVERSATIONS
UNION ALL
SELECT 'target_tasks', COUNT(*) FROM PURGE_TARGET_TASKS
UNION ALL
SELECT 'target_routes', COUNT(*) FROM PURGE_TARGET_ROUTES;

BEGIN;

DELETE FROM CAMEL_FLOW_IDEMPOTENCY
WHERE FLOW_TYPE IN ('agent.conversation', 'agent.chat.memory')
  AND FLOW_ID IN (SELECT CONVERSATION_ID FROM PURGE_TARGET_CONVERSATIONS);

DELETE FROM CAMEL_FLOW_EVENT
WHERE FLOW_TYPE IN ('agent.conversation', 'agent.chat.memory')
  AND FLOW_ID IN (SELECT CONVERSATION_ID FROM PURGE_TARGET_CONVERSATIONS);

DELETE FROM CAMEL_FLOW_SNAPSHOT
WHERE FLOW_TYPE IN ('agent.conversation', 'agent.chat.memory')
  AND FLOW_ID IN (SELECT CONVERSATION_ID FROM PURGE_TARGET_CONVERSATIONS);

DELETE FROM CAMEL_FLOW_IDEMPOTENCY
WHERE FLOW_TYPE IN ('agent.task', 'agent.task.lock')
  AND FLOW_ID IN (SELECT TASK_ID FROM PURGE_TARGET_TASKS);

DELETE FROM CAMEL_FLOW_EVENT
WHERE FLOW_TYPE IN ('agent.task', 'agent.task.lock')
  AND FLOW_ID IN (SELECT TASK_ID FROM PURGE_TARGET_TASKS);

DELETE FROM CAMEL_FLOW_SNAPSHOT
WHERE FLOW_TYPE IN ('agent.task', 'agent.task.lock')
  AND FLOW_ID IN (SELECT TASK_ID FROM PURGE_TARGET_TASKS);

DELETE FROM CAMEL_FLOW_IDEMPOTENCY
WHERE FLOW_TYPE = 'agent.dynamicRoute'
  AND FLOW_ID IN (SELECT ROUTE_INSTANCE_ID FROM PURGE_TARGET_ROUTES);

DELETE FROM CAMEL_FLOW_EVENT
WHERE FLOW_TYPE = 'agent.dynamicRoute'
  AND FLOW_ID IN (SELECT ROUTE_INSTANCE_ID FROM PURGE_TARGET_ROUTES);

DELETE FROM CAMEL_FLOW_SNAPSHOT
WHERE FLOW_TYPE = 'agent.dynamicRoute'
  AND FLOW_ID IN (SELECT ROUTE_INSTANCE_ID FROM PURGE_TARGET_ROUTES);

DELETE FROM CAMEL_FLOW_EVENT
WHERE FLOW_TYPE = 'agent.conversation.index'
  AND TRY_PARSE_JSON(PAYLOAD_JSON):conversationId::STRING IN (SELECT CONVERSATION_ID FROM PURGE_TARGET_CONVERSATIONS);

COMMIT;
